### ISSUE TITLE
Homepage: Remove TDEX-CLI section for dex.vulpem.com

### ISSUE THREAD

**Issue by tiero** [vulpemventures/vulpemcom#38]
Remove TDEX-CLI section, in favor of dex.vulpem web app.

Taking a screenshot is more than enough.

**Comment by bordalix** [comment]
@tiero some questions:
1. should I keep TDEX Cli in the footer?
2. should I add dex.vulpem to the footer?

**Comment by tiero** [comment]
I think we can remove it from footer and navbar menu (ie. replacing entirely by dex.vulpem)

We can keep as title TDEX for this section tho
